### ISSUE TITLE
i cannot install 2

### ISSUE THREAD

**Issue by ModGamerBackup** [battlecatsultimate/bcu-assets#2]
Just asking how can i fix permission denied because when I drag file to terminal it says Permission Denied.

**Comment by ModGamerBackup** [comment]
what folder

**Comment by MandarinSmell** [comment]
You may need to visit our discord server, there is installation guide explained. In there, it says that you have to create folder and put BCU-Initializer/BCU-Installer jar file into that folder. This is because BCU will create subfolders like `BCU_lib`, `assets`, etc, so if you don't create folder, it will make folder where it's at messy.

Also, if it's about permission problem, it's not problem of BCU, but your system. Try to move BCU folder to desktop. If it still won't work, try to check if any anti virus program is blocking it, especially McAfee, or Avast, etc

**Comment by ModGamerBackup** [comment]
sure

**Comment by ModGamerBackup** [comment]
what is the link for bcu jar 0-5-0-47 installer so this can end

**Comment by ModGamerBackup** [comment]
i will be playing hacked battle cats (used by gg)

**Comment by ModGamerBackup** [comment]
i just want aku shield for units like mine: Devil Bee (from battle bees ultimate scratch)

**Comment by ModGamerBackup** [comment]
maker

**Comment by ModGamerBackup** [comment]
really im so stupid at this why or I'm not stupid?

**Comment by ModGamerBackup** [comment]
then how can i open bcu-0-5-0-47 it keeps saying java application launch fail
